### ISSUE TITLE
Commit message length

### ISSUE THREAD

**Issue by ziadkh0** [SublimeTextIssues/Merge#15]
* [x] It would be nice if the length of the commit message can be displayed.
* [x] And even nicer if rulers can set (eg. at 72 characters). (see https://github.com/SublimeTextIssues/Merge/issues/15#issuecomment-423491581)

**Comment by keith-hall** [comment]
> And even nicer if rulers can set (eg. at 72 characters).

this is possible:

https://news.ycombinator.com/item?id=18035294

**Comment by ziadkh0** [comment]
@keith-hall thank you

**Comment by FichteFoll** [comment]
Do you consider this request fixed or do you wish to rephrase it?

**Comment by ziadkh0** [comment]
@FichteFoll only the second point is fixed, the first point still holds

**Comment by FichteFoll** [comment]
Lenght as in characters (per line, entire) or words?

**Comment by ziadkh0** [comment]
@FichteFoll length in characters of the first line

**Comment by ziadkh0** [comment]
For me showing the line and column position in the commit message implemented in build 1075 resolves the first point :+1: 
So closing for now
