### ISSUE TITLE
Allow copying of commit hashes

### ISSUE THREAD

**Issue by JustSid** [SublimeTextIssues/Merge#20]
When viewing a commit, it's impossible to copy any of the hashes (hash of the commit itself or any of its parents). This makes copying them to the clipboard impossible, which I've now come to realize I do semi frequently.

Ideally I'd like to be able to select the hash (or a partial subset of the hash), and copy it. Alternatively just being able to copy the hash in some different way would also work.

**Comment by tommcc** [comment]
To address a specific part of your request: you can currently copy one hash at a time:

- Right-click the commit in the tree, then select Copy Commit Hash
- Click `...` button at top right when viewing a commit, then select Copy Commit Hash

It would be great if you could do the same for a selection of multiple commits, though.

**Comment by FichteFoll** [comment]
@JustSid does that suffice for your request or do you still want to request selecting a subset of the hash?

**Comment by JustSid** [comment]
@FichteFoll That actually perfectly solves my request, subset of the hash is just a bonus. Thanks @tommcc for pointing this out.

One thing I would say is that it isn't easy to discover. I'd expect copying the hash would be somewhere close to where the hash itself is displayed. But that's just a minor UI/UX thing, and might also just be my personal preference.
