### ISSUE TITLE
Not respecting file line ending while resolving conflicts on Windows

### ISSUE THREAD

**Issue by jfcherng** [SublimeTextIssues/Merge#22]
If files are using LF as the line ending on Windows, they are forced converted to use CRLF after resolving conflicts. This makes the whole file become different in the diff.

![gif](https://user-images.githubusercontent.com/6594915/45920212-b5aa1680-bed3-11e8-9f99-76884ff08126.gif)

Source repo: [reproduce.zip](https://github.com/SublimeTextIssues/Merge/files/2408026/reproduce.zip)

**Comment by ghost** [comment]
Thanks for the report @jfcherng.

I'm currently investigating this, and it should be fixed in the next build.

-Dylan

**Comment by jfcherng** [comment]
@dylanjohnston I am afraid that this is not fixed in a correct manner. Tested on build 1062. The file still gets CRLF after resolving conflicts. [Test repo](https://github.com/SublimeTextIssues/Merge/files/2408026/reproduce.zip) is the same one with the original post.

![gif](https://user-images.githubusercontent.com/6594915/46115222-8de6e580-c228-11e8-92dd-7d04729a5415.gif)

**Comment by jfcherng** [comment]
Fixed in 1063.
