### ISSUE TITLE
When pre-commit hook fails, commit message is lost

### ISSUE THREAD

**Issue by plinss** [SublimeTextIssues/Merge#27]
I use a pre-commit hook to perform linting checks. When an issue is found and the hook exits with a non-zero status, SublimeMerge correctly detects the issue and reports the hook failure, stopping the commit. However the commit message is cleared. It would be nice to preserve the message for the next commit attempt.

**Comment by ghost** [comment]
Hi @plinss,

Thanks for the feedback! 

I'm currently investigating this issue. You can expect to see it fixed in the next build of Sublime Merge.

Kind regards,
\- Dylan

**Comment by tchapeaux** [comment]
In the meantime, you can get the original commit message back with Edit > Undo

**Comment by plinss** [comment]
Verified fixed in build 1070
