### ISSUE TITLE
Rename Branch new name erased on backspace

### ISSUE THREAD

**Issue by willrowe** [SublimeTextIssues/Merge#29]
When renaming a branch the new name option is pre-filled with the same name as the target branch, but is not editable. If you press <kbd>Backspace</kbd> the entire name is deleted.

![rename branch](https://user-images.githubusercontent.com/7152423/46088388-53267400-c17a-11e8-9f1e-c939233dfc84.png)

I would expect it to be like this, or convert to this when <kbd>Backspace</kbd> is pressed:

![rename branch - expected](https://user-images.githubusercontent.com/7152423/46088678-e2cc2280-c17a-11e8-8c7b-d0b30a442f53.png)

**Comment by willrowe** [comment]
After further testing, I discovered that when the left arrow key is pressed it will go to the beginning of the new name and make it editable.
While this allows you to edit the current name, I still think it is somewhat unexpected to have it completely erased when pressing <kbd>Backspace</kbd>.

**Comment by FichteFoll** [comment]
Imo the the second `new_branch` just shouldn't be inserted when running that command. I won't judge on backspace removing the entire word because that's a different design decision that affects many other areas around the command palette.

**Comment by willrowe** [comment]
> Imo the the second new_branch just shouldn't be inserted when running that command.

I find it invaluable for fixing a typo or renaming to something very similar, being able to clear it out quickly with <kbd>Backspace</kbd> makes it worth it for me.

> I won't judge on backspace removing the entire word because that's a different design decision that affects many other areas around the command palette.

That's a good point, knowing that I can just use the arrow keys is sufficient.

My main reason for opening this was wanting to be able to edit the original name quickly, since you can do this with arrow key, I will close this.
