### ISSUE TITLE
Opening a new repo with command palette open causes it to stick 

### ISSUE THREAD

**Issue by todsleeman** [SublimeTextIssues/Merge#32]
If you open a new repo whilst having the command palette open on an existing window, the new window will have the command palette stuck open and unable to be removed.

Steps to reproduce:
- Open a sublime merge window
- Open the command palette
- Open a different repo using Command + Shift + O

Results:
- The command palette will be stuck open

MacOS: v10.14
Sublime Merge: Build 1075

**Comment by FichteFoll** [comment]
Please file this issue against the new official repo referenced in the Readme.
