### ISSUE TITLE
Commits with a tag but no branch are not visible

### ISSUE THREAD

**Issue by pzac** [SublimeTextIssues/Merge#33]
This

![image](https://user-images.githubusercontent.com/272278/49440045-ee634780-f7c2-11e8-9301-cb075abdcfd3.png)

Appears as

![image](https://user-images.githubusercontent.com/272278/49440073-00dd8100-f7c3-11e8-8b44-b8ff56556a67.png)

`tag-2` is missing

**Comment by FichteFoll** [comment]
Please open this issue at https://github.com/sublimehq/sublime_merge instead.
